### PR TITLE
Revert "Created View companies page and worked on responsiveness "

### PR DESCRIPTION
**Pull request by Eniola4031**
Reverts Eniola4031/echoCV#42

### CODE REVIEW

**Comment by Eniola4031** [comment]
You created another add company page instead of modifying the one i already did and it is also not the same as the design.
There is already a web route for the view_company page, it will only cause conflict.

**Comment by Janetsomehow** [comment]
There's no view_company page here

**Comment by Janetsomehow** [comment]
proof

**Comment by Janetsomehow** [comment]
And i worked on improving the responsiveness of the add_company page

**Comment by Eniola4031** [comment]
Try to click on the new chart button on the homepage. It contains the view companies you're trying to create. I added the routing to redirect to that page cos it's linked page has not been created yet. check out "add_chart" page.
The add_company page is not responsive on smaller and bigger screen from my side, maybe you should check it again.

**Comment by Janetsomehow** [comment]
Alright

**Comment by Janetsomehow** [comment]
Based on the mobile view of that add_chart page, the page might not look exactly as the design suggests.

**Comment by Janetsomehow** [comment]
Is there any route for single company already?

**Comment by moneya** [comment]
@Janetsomehow   
image

**Comment by Janetsomehow** [comment]
I created that
Just wanted to be sure.

**Pull request merged**
